version: '3.5'

services:
  jbong:
    image: janshercs/hello-server
    ports:
      - 8081:8080
    networks:
      - kong-quickstart-net
    command: ["./hello_server", "--name", "jbong"]
  janshercs:
    image: janshercs/hello-server
    ports:
      - 8082:8080
    networks:
      - kong-quickstart-net
    command: ["./hello_server", "--name", "janshercs"]

networks:
  kong-quickstart-net:
    name: kong-quickstart-net
    external: true
