# Start with the official Golang image as the build environment
FROM golang:1.20-alpine AS builder

# Copy the go mod and sum files
COPY . /app/
WORKDIR /app

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN ls
RUN pwd
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o hello_server ./cmd/server

# Start a new stage from scratch
FROM alpine:latest

# Set the Current Working Directory inside the container
WORKDIR /root/

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /app/hello_server .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./hello_server", "--name", "Docker"]
